# Build and run tests on push to any branch except master

name: check-branch

on:
  push:
    branches:
      - '**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2

      - name: Initialize Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - run: npm ci

      - run: npm run build

      - run: npm run test
