name: Check branch

on:
  push:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Initialize Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - run: npm ci

      - run: npm run build

      - run: npm run test
